zh_CN = {
    "Repair Blend files, some of the files open Blend will flash back, you can use this plug-in repair": "修复Blend文件,部分文件打开时Blend会闪退,可以使用此插件进行修复",
    "Top toolbar and bottom of preferences": "顶部工具栏和偏好设置底部",
    "Popup fix window": "弹出修复窗口",
    "Popup fix blend file window": "弹出修复Blend文件窗口",
    "Load data": "加载数据",
    "Load the file data that needs to be fix": "加载需要修复的文件数据",
    "Import data": "导入数据",
    "Importing data from error files": "导入错误文件的数据",
    "Import complete!": "导入完成!",
    "Switch select": "切换选择",
    "Switch all or cancel select": "切换全选或者取消全选",
    "Not find item": "未找到项",
    "Clear list": "清理列表",
    "Clear fix list": "清理修复的列表",
    "Error File Path": "损坏文件路径",
    "Import selected": "导入所选",
    "1.Bottom select a broken .blend file": "1.底部选择一个损坏的.blend文件",
    "2.Click Load data": "2.点击加载数据",
    "3.Select any import option and click Import selected": "3.选择任意一种导入选项,然后点击导入所选,将会导入对应的数据到当前工程中",
    "Total": "共",
    "Selected": "已选",
    "Error File Path:": "损坏文件路径:",
    "Fix file": "修复文件",
    "Exit": "退出",
}
